### ISSUE TITLE
Move to an alternative for path_provider supporting web too

### ISSUE THREAD

**Issue by martingwerder** [cyber-geiger/toolbox-storage#33]
**Describe the bug**
path_provider does not support the web platform. This should be fixed. it is currently blocked by flutter/flutter#45296.

**Environmental information**
- web platform
- Any SDK

**To Reproduce**
Check dependencies with flutter upgrade 

**Expected behavior**
should run on web too

**Screenshots**
none

**Additional context**
none

**Comment by mgwerder** [comment]
There seems to be no alternative in the Flutter-Universe. Closing for now
