### ISSUE TITLE
Increasing max storage constraint 

### ISSUE THREAD

**Issue by BananaEgg** [cyber-geiger/toolbox-storage#34]
The max file size accepted by the CERT's is 10MB, although the file size is usually about 1MB.
We need to be able to store files up to 10MB

**Comment by martingwerder** [comment]
This is partially addressed in the release 0.6.22. Any new database wil be created with a constraint of 10MB.

**Comment by BananaEgg** [comment]
After upgrading to 0.6.2 I'm able to store data, but I'm getting a timeout error while sending files.

Exception has occurred.
StorageException (StorageException:Remote call failed at 
#0      new SerializedException (package:geiger_localstorage/src/storage_exception.dart:39:44)
#1      new StorageException (package:geiger_localstorage/src/storage_exception.dart:116:9)
#2      PassthroughController._remoteCall (package:geiger_api/src/communication/passthrough_controller.dart:78:13)
<asynchronous suspension>
#3      PassthroughController.addOrUpdate (package:geiger_api/src/communication/passthrough_controller.dart:106:18)
<asynchronous suspension>
#4      GeigerApiConnector.writeToGeigerStorage (package:il_geiger_kpmg_onprem/assets/geiger_connector.dart:300:7)
<asynchronous suspension>

cause:
CommunicationException:timeout reached at 
#0      new SerializedException (package:geiger_localstorage/src/storage_exception.dart:39:44)
#1      new CommunicationException (package:geiger_api/src/communication/communication_exception.dart:9:9)
#2      Listener.waitForResult (package:geiger_api/src/communication/communication_helper.dart:43:13)
<asynchronous suspension>
#3      CommunicationHelper.sendAndWait (package:geiger_api/src/communication/communication_helper.dart:63:18)
<asynchronous suspension>
#4      PassthroughController._remoteCall (package:geiger_api/src/communication/passthrough_controller.dart:68:22)
<asynchronous suspension>
#5      PassthroughController.addOrUpdate (package:geiger_api/src/communication/passthrough_controller.dart:106:18)
<asynchronous suspension>
#6      GeigerApiConnector.writeToGeigerStorage (package:il_geiger_kpmg_onprem/assets/geiger_connector.dart:300:7)
<asynchronous suspension>
)

**Comment by martingwerder** [comment]
This should be fixed now. Can you confirm?

**Comment by BananaEgg** [comment]
Yes it works, 
Thank you @martingwerder !
