### ISSUE TITLE
I got an error saying that I can't load the Master Node after the updated version (0.6.26).

### ISSUE THREAD

**Issue by Cftn** [cyber-geiger/toolbox-storage#39]
**Describe the bug**
I got an error saying that I can't load the Master Node after the updated version (0.6.26). 
Everything is same as before nothing changed. Only the version has been updated.

I think this is main problem ``Unable to load asset: assets/store/store.data``.

**Screenshots**
If applicable, add screenshots to help explain your problem (please: no code in screenshots).

========= Tested on UI flutter
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/15152117/153871323-0bfb2b8a-0014-4fd8-81c7-da6c6ada1fc0.png">

<img width="965" alt="image" src="https://user-images.githubusercontent.com/15152117/153871660-45e550f1-50b3-44e6-a0d1-3e44e4fffe2c.png">

======== Tested on Single Plugin (That called Initialized data) 
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/15152117/153871916-790c46b6-d5d0-4c4f-9341-ad4b259f8876.png">

**Comment by martingwerder** [comment]
It seems that the package is broken currently. 

As a workarround you may copy the file assets/store/store.data from github into your local file structure (same directories) and it should work.

I will investigate whether the file is missing or what else the issue is and release a bug fix.

**Comment by martingwerder** [comment]
I think I have found the issue. Can you confirm that it is gone when using 0.6.27?

**Comment by Cftn** [comment]
Yes. It works well. Thanks a lot.
>>The error(Unable to load asset: assets/store/store.data) solved. 


However, there are two issues. 

1. Can't load the master Node using GEIGER API.
>>It should create the storage as SQLite (that means create Master Node themselves) before calling the GEIGER API to get the Master node. It had not been required before.

![image](https://user-images.githubusercontent.com/15152117/153933022-86eff233-aca0-4356-8f26-0fe4166d861f.png)


2. The listener only works inside each plugin, not connection with the others using GEIGER API.
>>  It does not work if I get the controller (Master node) using GEIGER API. It only works well delivering the controller (Master node) as a parameter, I tested it using two different plugins.
>> Would you please share the listener example of interacting connections (two files, sender and receiver )? I checked a new example but it only considered aspects of independence I think.
It should consider multiple connections such as two Android apps (GEIGER tool-box and GEIGER indicator, not only one App (GEIGER tool-box).


I appreciate your work and please let me know if I something misunderstood.
By the way, I will try to have a call with you.

**Comment by martingwerder** [comment]
That looks to me like another problem of the path_provider. Out from experiences we know that MacOS support is bad and they are working heavily to get it working. It is definitely not related to this issue. 

If it is a MacOS machine: we will have to wait for an update from the path_provider team. 
If not: Please write a separate issue *with an MWE* to reproduce your issue.
