### ISSUE TITLE
There is no data yet accepting UI data.

### ISSUE THREAD

**Issue by Cftn** [cyber-geiger/toolbox-storage#43]
Thank you so much Martin. 
@martingwerder, there is no data yet excepting UI data. I am not sure about which color of TLP because there is no data. The only exist when I tested on Indicator alone.

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/15152117/155351463-90bb2ec4-eaa1-4304-b756-620407d03588.png">

_Originally posted by @Cftn in https://github.com/cyber-geiger/toolbox-storage/issues/42#issuecomment-1048908709_

**Comment by nosadaniel** [comment]
@martingwerder 
It seems the ```:Global:threats```  path, TLP is still red.

I don't know if that could be the problem.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/33612084/155388555-1dc25e56-d700-4a32-a853-44bc1a534961.png">

**Comment by martingwerder** [comment]
Please stick to the template when creating issues just a screenshot of a random error message/dump excerpt does not make an issue reproducable or diagnosable and reproducability is needed to help you. 

Second: Please indicate versions (also in the template), platforms, and steps to reproduce your issue (*including* MWE; Issues without an MWE are treatet with the lowest priority). 

And third: be precise. The data is clearlyVersion 0.6.37 has already a new store set (derived from yours) all containing entries TLP:WHITE. All it teakes is a fresh install to initialize the database (Reinstall if you cannot find the database. For the moment I cannot see an issue with the most frequent version closing this issue as invalid.
