### ISSUE TITLE
Regarding initial data creation

### ISSUE THREAD

**Issue by Cftn** [cyber-geiger/toolbox-storage#45]
I tested using UI from Nosa, UI from Luong and indicator alone. 
But, there are nothing. I attached source code and log. 

### indicator 

```
void main() async {

  final localMaster =
  (await getGeigerApi("", GeigerApi.masterId, Declaration.doShareData))
  !;
  Storage.controller = localMaster.getStorage();

  print(await  Storage.controller!.dump(":"));
```

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/15152117/155513677-d5fd6373-9457-4cb0-ad78-71d9af2e2a0c.png">

### UI-flutter 

```
  Future<void> _initLocalStorage() async {
    try {
      _api = await _geigerApiConnector.getLocalMaster;
      _storageController = await _api.getStorage()!;
      log("StorageController initialize successfully $_storageController");

      log("Dump after initialize ==> ${await _storageController.dump(":")}");

    } catch (e) {
      log("Failed to get StorageController ===> \n $e");
    }
  }
```

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/15152117/155512707-b140afe7-c5a7-4ffd-b24f-9bcdf30a4409.png">

### Flutter from Luong 

```
Future<bool> initMasterPlugin() async {
    final bool initGeigerAPI = await masterApiConnector.connectToGeigerAPI();
    if (initGeigerAPI == false) return false;
    final bool initLocalStorage =
        await masterApiConnector.connectToLocalStorage();
    if (initLocalStorage == false) return false;
    final bool regPluginListener =
        await masterApiConnector.registerPluginListener();
    final bool regStorageListener =
        await masterApiConnector.registerStorageListener();

    var str =await masterApiConnector.dumpLocalStorage(':');
    print(str);
    runIndicator('1234-1234-1234-1234');

    isMasterStarted = true;
    return regPluginListener && regStorageListener;
  }
```

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/15152117/155511913-a0f1b72f-4319-4055-ad83-5c2e2f31343b.png">

**Comment by martingwerder** [comment]
Can you please replace ```Declaration.doShareData``` with ```Declaration.doNotShareData```. If you share data the possibility of seeing data is greatly reduced. 

If the problem persists use the newest version 0.6.38 and post the logs obtained. 

I currently use the following test which is working for me:
```
    test("initial data not found", () async {
      GeigerApi localMaster = (await getGeigerApi(
          "", GeigerApi.masterId, Declaration.doNotShareData))!;
      StorageController sc = localMaster.getStorage()!;
      expect((await sc.get(":Global:threats")).path, ':Global:threats');
    });
```

**Comment by Cftn** [comment]
In version 0.6.38, The indicator internal test only works when I am given the assets folder which has 'data file (store.data)'. "Declaration" is no matter, both work fine on indicator testing alone.  

The others do not work (two applications) same test condition as indicator.  

I tested on Samsung galaxy.  I always uninstall and reinstall again.

### Indicator
![image](https://user-images.githubusercontent.com/15152117/155569001-8d0cb78e-4345-4766-9bac-7c550ea9cbd8.png)


### UI
![image](https://user-images.githubusercontent.com/15152117/155568884-738ec254-6a64-49a9-9a02-7e8c0bee15f8.png)


### Flutter
![image](https://user-images.githubusercontent.com/15152117/155569048-daa89b98-ebba-40fd-95a9-e5f77bf9da07.png)


Thanks a lots

**Comment by Cftn** [comment]
In version 0.6.38, The indicator internal test only works when I am given the assets folder which has 'data file (store.data)'. "Declaration" is no matter, both work fine on indicator testing alone.  

The others do not work (two applications) same test condition as indicator.  

I tested on Samsung galaxy.  I always uninstall and reinstall again.

### Indicator
![image](https://user-images.githubusercontent.com/15152117/155569001-8d0cb78e-4345-4766-9bac-7c550ea9cbd8.png)


### UI
![image](https://user-images.githubusercontent.com/15152117/155568884-738ec254-6a64-49a9-9a02-7e8c0bee15f8.png)


### Flutter
![image](https://user-images.githubusercontent.com/15152117/155569048-daa89b98-ebba-40fd-95a9-e5f77bf9da07.png)


Thanks a lots
