### ISSUE TITLE
request to let plugin explicitly initial data 

### ISSUE THREAD

**Issue by nosadaniel** [cyber-geiger/toolbox-storage#48]
Would it be possible for a plugin to explicitly initialized default data(if needed), instead of the localstorage automatically initializing the data from the asset folder?
We are currently having a conflict with some of the data that is being initiated by default.

Thanks.

**Comment by nosadaniel** [comment]
@martingwerder any update on this.
we are currently blocked by this.

**Comment by martingwerder** [comment]
The file has been updated in 0.6.44 and should reflect the initial data provided by the cloud again. Initialization can be blocked by providing an empty file. *DO NOT USE AN EMPTY FILE FOR PRODUCTION*.

Can you confirm that this issue is solved with 0.6.44?

**Comment by davidkernfhnw** [comment]
Thank you for the quick fix on your side. 
By trying to build the application I get the following error regarding the sqlite version.

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/97611154/160629292-b6daa3ee-7398-417e-b3a3-9268d10518b5.png">

Used Versions:
  geiger_api: ^0.7.3
  geiger_localstorage: ^0.6.44

Flutter Version:  2.10.3

Tested on Android Emulator


Thank you for your help Martin

**Comment by martingwerder** [comment]
Hmmm. Can you try with the latest stable flutter (2.10.4)? I think the upgrades to the test framework of flutter were severe.
 
If an upgrade does not solve the problem: can you post the output of "flutter doctor -v"

**Comment by davidkernfhnw** [comment]
Thank you for your suggestions. Unfortunately I could not solve the issue by upgrading Flutter to 2.10.4 
Therefore I send you the requested output of "flutter doctor -v" 

![image](https://user-images.githubusercontent.com/97611154/160857612-bf5e9bdb-631d-49db-b7a5-46d1d07d15c6.png)

![Bildschirmfoto 2022-03-30 um 16 23 33](https://user-images.githubusercontent.com/97611154/160857879-af368916-2306-4890-83d2-0ddb2dd45b0a.png)

Thanks for your help.

**Comment by martingwerder** [comment]
A new version (0.6.45) is available. It downgrades the dependency to solve your conflict. Furthermore, a flag has been added (GenericController.preloadData) which may be set to false prior to the first use of the database. This should buy you some time. Please note that this feature was introduced as deprecated and will disapear in the very near future again (in April).

Can you confirm that the issue is gone?

**Comment by davidkernfhnw** [comment]
Thank you, the issue is gone and it works as expected.
