### ISSUE TITLE
How to search for a Node using searchCriteria

### ISSUE THREAD

**Issue by nosadaniel** [cyber-geiger/toolbox-storage#51]
I was told by Martin that I can get access to a node by using an id that exists in a nodePath,  without specifying the full node path name but I can't figure out how I can do this. for example :Global:recommendation:1123.

I tried getting the above node by doing this ```await storageController.search((SearchCriteria(searchPath: "1123"));```
unfortunately, I always get an empty list.

Maybe am doing something wrong.

Note: the node path already exists in the storage
geiger_localStorage: 0.6.45

Thanks for the assistance.

**Comment by martingwerder** [comment]
In the development tree under ```nosaTests() -> 20220412 - Sample code as requested for lookup of node```.

For a full list of the evaluation criteria see FlutterDoc ```SearchCriteria.evaluate(...)```. Please note: The preloaded file was wrong. The type was missing as specified in the spec. The Wiki has now an example which is parseable by the current parser and is sufficient. Have a look at the sample code and let us know if you need more.

**Comment by nosadaniel** [comment]
Thanks for the feedback.
I tried using a specific recommendationId in the sample code but I still got an empty list even when the recommendation already exist in the store.

```
test("searching everywhere for recommendation", () async {
      // get a Node recommendation
      String recomId = "b7a27749-8686-47df-84eb-a92e6cd4a640";
      List<Node> nl2 = await storageController!
          .search(SearchCriteria(searchPath: ":", nodeValueType: recomId));

      print(
          "searching everywhere recommendations resulted in ${nl2.length} nodes");
    });
    
    ```
