### ISSUE TITLE
Problems getting started with package

### ISSUE THREAD

**Issue by mgwerder** [cyber-geiger/toolbox-storage#9]
Hi Martin,
I have tried but failed to test the new API.

Environment:
- Mac OS
- Android Simulator: Pixel 4a API 30 (android-x86)
- flutter version:
Flutter 2.5.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffb2ecea52 (11 days ago) • 2021-09-17 15:26:33 -0400
Engine • revision b3af521a05
Tools • Dart 2.14.2

How did I import the lib:
import 'package:geiger_localstorage/geiger_localstorage.dart' as ToolboxAPI;

Test 1: with SqliteMapper
- Failed to initialize the Controller
```dart
ToolboxAPI.StorageController geigerToolboxStorageController =
      ToolboxAPI.GenericController('MI-Cyberrange',
          ToolboxAPI.SqliteMapper('jdbc:sqlite:./dbFileName.sqlite'));
```
- Error:
  ```dart
  field conn was not initialized
  ```
 

Test 2: with DummyMapper
- Succeeded to initialize the controller
```dart
ToolboxAPI.StorageController geigerToolboxStorageController =
      ToolboxAPI.GenericController('MI-Cyberrange', ToolboxAPI.DummyMapper());
```
- Failed to add node
```dart
void sendToGeiger(int level, double newScore) {
    try {
      ToolboxAPI.Node node = geigerToolboxStorageController.get(':score-node');
      node.addValue(ToolboxAPI.NodeValueImpl('score', '$newScore'));
      node.addValue(ToolboxAPI.NodeValueImpl('level', '${currentUser!.level}'));
      geigerToolboxStorageController.update(node);
      _testAPI();
    } catch (e) {
      // print(e.toString());
      ToolboxAPI.Node node = ToolboxAPI.NodeImpl('score-node');
      geigerToolboxStorageController.add(node);
      node.addValue(ToolboxAPI.NodeValueImpl('score', '$newScore'));
      node.addValue(ToolboxAPI.NodeValueImpl('level', '${currentUser!.level}'));
      geigerToolboxStorageController.update(node);
      _testAPI();
    }
  }
```
- Error:
 ```dart
Node does already exist
```

And if I ignore the node checking, there was other error:
```dart
void sendToGeiger(int level, double newScore) {
    ToolboxAPI.Node node = geigerToolboxStorageController.get(':score-node');
    node.addValue(ToolboxAPI.NodeValueImpl('score', '$newScore'));
    node.addValue(ToolboxAPI.NodeValueImpl('level', '${currentUser!.level}'));
    geigerToolboxStorageController.update(node);
    _testAPI();
  }
```

- Error: 
 ```dart
Node not found
```

I also tried to run the test: flutter test in the toolbox-storage (branch chore/dart-migration), but all the tests were failed.

Please note that the test have been done on lacking of documentation, so there are maybe some environment configuration missing. So if you have more documentation on this, I am happy to reproduce the tests.

Best regards,
Luong NGUYEN

**Comment by mgwerder** [comment]
Not sure what the problem is with checking out the branch and running the tests. Althoug it is a development branch you picked at least most of the tests do/should work. I do not have a Mac at hand so it is kind of hard to reproduce in every facet.

One thing I can see: Exceptions should carry more information such as node names or value names to give better indication of error. I opened up issue #10 for this.

Another thing I can see: the documentation in the readme is wrong. It still shows the "JDBC String".

Working on this. Hopefully I can provide better feedback until end of day.

**Comment by mgwerder** [comment]
I added some sample code in the dev release 0.5.1 which should address your issues. Does that help?

**Comment by luongnv89** [comment]
@mgwerder I have made some tests with the new version. Unfortunately there are still some issues.
Test 1 (sqlite)- I had the same problem/ same error. Do I need to manually install sqlite on my phone? 
Test 2 (dummyMapper) - It worked well if I use `addOrUpdate()` for adding node, and I saw that it went to creating a new node every time I call the function (without reloading the app), so I am not sure that is due to DummyMapper or there is a problem in API.

```
void sendToGeiger(int level, String random) {
    try {
      print('Trying to get a node');
      ToolboxAPI.Node node = geigerToolboxStorageController.get(':score-node');
      node.addValue(ToolboxAPI.NodeValueImpl('score', '$random'));
      node.addValue(ToolboxAPI.NodeValueImpl('level', '$level'));
      geigerToolboxStorageController.update(node);
      _testAPI();
    } catch (e) {
      print('Creating a new node');
      // print(e.toString());
      ToolboxAPI.Node node = ToolboxAPI.NodeImpl('score-node');
      geigerToolboxStorageController.addOrUpdate(node);
      node.addValue(ToolboxAPI.NodeValueImpl('score', '$random'));
      node.addValue(ToolboxAPI.NodeValueImpl('level', '$level'));
      geigerToolboxStorageController.update(node);
      _testAPI();
    }
  }
```

Also, it would be great if you can tell me how do you setup your environment for testing

**Comment by luongnv89** [comment]
@tschai-yim Thank for your reply, I have already tested the `sqlite3_flutter_libs` but it did not work. Could you please tell me on which environment you are testing? It might due to my setup.

**Comment by nosadaniel** [comment]
Same issues testing on iPhone 13 simulator:

Test environment:

Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 3595343e20 (2 days ago) • 2021-09-30 12:58:18 -0700
Engine • revision 6ac856380f
Tools • Dart 2.14.3


How did i use it:
added both sqlite3_flutter_libs: ^0.5.1  and geiger_localstorage: ^0.5.1 in pubspec.yaml file.

I tried initialising it in before my ui loads but it stills fails: see error screenshot and error log below.

Suggestion: it's possible to let StorageController  or conn returns a Future, that way the Ui just have to use the await keyword to wait until  its initialises. flutter Firebase uses this kind of technique. 

https://firebase.flutter.dev/docs/overview



error log:
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field 'conn' has not been initialized.
#0      SqliteMapper.conn (package:geiger_localstorage/src/db/mapper/sqlite_mapper.dart)
#1      SqliteMapper.initialize (package:geiger_localstorage/src/db/mapper/sqlite_mapper.dart:68:7)
#2      new SqliteMapper (package:geiger_localstorage/src/db/mapper/sqlite_mapper.dart:59:9)
#3      main (package:example/main.dart:9:36)
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:145:25)
#5      _rootRun (dart:async/zone.dart:1428:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _runZoned (dart:async/zone.dart:1863:10)

**Comment by nosadaniel** [comment]
this is an issues.
getStorage method return instance of storageController and acreated testdb file which can't be access in android.

The partial fix 
flutter 2.5.1
geiger_api 0.5.0
```

Future<StorageController?> localGeigerApi() async {
    final GeigerApi? localDummyData =
        await getGeigerApi('', GeigerApi.MASTER_ID, Declaration.doNotShareData);
    //SimpleEventListner masterListener;

    final StorageController? _masterController = localDummyData!.getStorage();

    return _masterController;
  }


```

**Comment by martingwerder** [comment]
This isue duplicates isues #14 and #15 which need addressing. The main problem is that we need to add auto detection for the platform as depending on the platform writeable directories differ.

Update should be available by next Monday latest.
